# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Data' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Data

  target 'DataTests' do
    # Pods for testing
  end

end

target 'Domain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Domain

end

target 'Infra' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Infra
  pod 'Alamofire', '~>5.6.1'

  target 'InfraTests' do
    # Pods for testing
    pod 'Alamofire', '~>5.6.1'
  end

end
